classDiagram
direction LR

class Asset {
+int id
+string ticker
+string name
+string type
+float current_price
+datetime last_update
}

class Transaction {
+int id
+int asset_id
+int wallet_id
+datetime date
+string type
+float quantity
+float price
+float costs
}

class User {
+int id
+string username
+string email
+string hashed_password
+bool is_admin
}

class Wallet {
+int id
+string name
+string? description
+int user_id
}

class Annotations {
+int id
+bool public
+string title
+string annotation
+string annotation_type
+int target_id
}

User "1" --> "0..*" Wallet : wallets
Wallet "1" --> "0..*" Transaction : transactions
Asset "1" --> "0..*" Transaction : transactions

Transaction --> Wallet : wallet
Transaction --> Asset : asset
Wallet --> User : user

Annotations --> Transaction : annotation_of
Annotations --> Wallet : annotation_of
Annotations --> Asset : annotation_of